spring:
  application.name: zip-importer
  datasource:
    url: jdbc:h2:file:./data/imports;AUTO_SERVER=TRUE
    username: sa
    password: ""
  sql.init.mode: always

importer:
  mode: local
  path: ./sample/import-{date}.zip
  schema-entry: schema.json
  csv-entry: data.csv
  delimiter: ","
  batch-size: 500
  run-on-startup: false
  zone: Europe/Warsaw
  sftp:
    host: localhost
    port: 22
    username: importer
    known-hosts: ${user.home}/.ssh/known_hosts
    allow-unknown-host: false
