create table if not exists imported_row (
  id bigint generated by default as identity primary key,
  source_file varchar(1000) not null,
  row_number bigint not null,
  payload clob not null,
  imported_at timestamp with time zone not null
);
create index if not exists idx_imported_row_source on imported_row(source_file);
