create table import_execution (
  id uuid primary key,
  import_name varchar(100) not null,
  source_file varchar(1000) not null,
  status varchar(20) not null check (status in ('RUNNING', 'COMPLETED', 'FAILED')),
  imported_rows bigint,
  error_message varchar(2000),
  started_at timestamp with time zone not null,
  completed_at timestamp with time zone
);

create table imported_row (
  id bigint generated by default as identity primary key,
  execution_id uuid not null references import_execution(id),
  source_file varchar(1000) not null,
  row_number bigint not null,
  record_type varchar(50) not null,
  business_key varchar(255) not null,
  payload clob not null,
  imported_at timestamp with time zone not null,
  constraint uq_imported_row_execution_row unique(execution_id, row_number)
);

create index idx_imported_row_source on imported_row(source_file);
create index idx_import_execution_status on import_execution(status, started_at);
